

i2c:
  id: bus_i2c
  sda: 6
  scl: 7
  scan: true
  frequency: 400kHz

wk2132_i2c:   ### I2C Expander z.B. DFRobot DFR0627
  - address: 0x10
    i2c_id: bus_i2c
    id: DFR0627_bridge_i2c_1
    uart:
      - id: i2c_uart_1
        channel: 0
        baud_rate: 2400
        parity: NONE
        stop_bits: 1
      - id: i2c_uart_2
        channel: 1
        baud_rate: 2400
        parity: NONE
        stop_bits: 1
  - address: 0x30
    i2c_id: bus_i2c
    id: DFR0627_bridge_i2c_2
    uart:
      - id: i2c_uart_3
        channel: 0
        baud_rate: 2400
        parity: NONE
        stop_bits: 1
      - id: i2c_uart_4
        channel: 1
        baud_rate: 2400
        parity: NONE
        stop_bits: 1
  - address: 0x50
    i2c_id: bus_i2c
    id: DFR0627_bridge_i2c_3
    uart:
      - id: i2c_uart_5
        channel: 0
        baud_rate: 2400
        parity: NONE
        stop_bits: 1
      - id: i2c_uart_6
        channel: 1
        baud_rate: 2400
        parity: NONE
        stop_bits: 1
  - address: 0x70
    i2c_id: bus_i2c
    id: DFR0627_bridge_i2c_4
    uart:
      - id: i2c_uart_7
        channel: 0
        baud_rate: 2400
        parity: NONE
        stop_bits: 1
      - id: i2c_uart_8
        channel: 1
        baud_rate: 2400
        parity: NONE
        stop_bits: 1

sensor:
  # =========================
  # Modul 1 – Adresse 0x10
  # =========================
  
  - platform: ultramaxx
    id: ultramaxx_1
    uart_id: i2c_uart_1

    serial_number:
      name: "1 Seriennummer"
    total_energy:
      name: "1 Gesamtenergie"
    total_volume:
      name: "1 Gesamtvolumen"
    power:
      name: "1 Leistung"
    flow:
      name: "1 Flow"
    temp_flow:
      name: "1 Vorlauf Temperatur"
    temp_return:
      name: "1 Rücklauf Temperatur"
    temp_diff:
      name: "1 Temperatur Differenz"
    meter_time:
      name: "1 Zeitstempel"
    operating_time:
      name: "1 Betriebszeit"
    firmware_version:
      name: "1 Firmware Version"
    software_version:
      name: "1 Software Version"
    access_counter:
      name: "1 Zugriffszähler"
    status_text:
      name: "1 Status"


  - platform: ultramaxx
    id: ultramaxx_2
    uart_id: i2c_uart_2

    serial_number:
      name: "2 Seriennummer"
    total_energy:
      name: "2 Gesamtenergie"
    total_volume:
      name: "2 Gesamtvolumen"
    power:
      name: "2 Leistung"
    flow:
      name: "2 Flow"
    temp_flow:
      name: "2 Vorlauf Temperatur"
    temp_return:
      name: "2 Rücklauf Temperatur"
    temp_diff:
      name: "2 Temperatur Differenz"
    meter_time:
      name: "2 Zeitstempel"
    operating_time:
      name: "2 Betriebszeit"
    firmware_version:
      name: "2 Firmware Version"
    software_version:
      name: "2 Software Version"
    access_counter:
      name: "2 Zugriffszähler"
    status_text:
      name: "2 Status"


  # =========================
  # Modul 2 – Adresse 0x30
  # =========================

  - platform: ultramaxx
    id: ultramaxx_3
    uart_id: i2c_uart_3

    serial_number:
      name: "3 Seriennummer"
    total_energy:
      name: "3 Gesamtenergie"
    total_volume:
      name: "3 Gesamtvolumen"
    power:
      name: "3 Leistung"
    flow:
      name: "3 Flow"
    temp_flow:
      name: "3 Vorlauf Temperatur"
    temp_return:
      name: "3 Rücklauf Temperatur"
    temp_diff:
      name: "3 Temperatur Differenz"
    meter_time:
      name: "3 Zeitstempel"
    operating_time:
      name: "3 Betriebszeit"
    firmware_version:
      name: "3 Firmware Version"
    software_version:
      name: "3 Software Version"
    access_counter:
      name: "3 Zugriffszähler"
    status_text:
      name: "3 Status"


  - platform: ultramaxx
    id: ultramaxx_4
    uart_id: i2c_uart_4

    serial_number:
      name: "4 Seriennummer"
    total_energy:
      name: "4 Gesamtenergie"
    total_volume:
      name: "4 Gesamtvolumen"
    power:
      name: "4 Leistung"
    flow:
      name: "4 Flow"
    temp_flow:
      name: "4 Vorlauf Temperatur"
    temp_return:
      name: "4 Rücklauf Temperatur"
    temp_diff:
      name: "4 Temperatur Differenz"
    meter_time:
      name: "4 Zeitstempel"
    operating_time:
      name: "4 Betriebszeit"
    firmware_version:
      name: "4 Firmware Version"
    software_version:
      name: "4 Software Version"
    access_counter:
      name: "4 Zugriffszähler"
    status_text:
      name: "4 Status"


  # =========================
  # Modul 3 – Adresse 0x50
  # =========================

  - platform: ultramaxx
    id: ultramaxx_5
    uart_id: i2c_uart_5

    serial_number:
      name: "5 Seriennummer"
    total_energy:
      name: "5 Gesamtenergie"
    total_volume:
      name: "5 Gesamtvolumen"
    power:
      name: "5 Leistung"
    flow:
      name: "5 Flow"
    temp_flow:
      name: "5 Vorlauf Temperatur"
    temp_return:
      name: "5 Rücklauf Temperatur"
    temp_diff:
      name: "5 Temperatur Differenz"
    meter_time:
      name: "5 Zeitstempel"
    operating_time:
      name: "5 Betriebszeit"
    firmware_version:
      name: "5 Firmware Version"
    software_version:
      name: "5 Software Version"
    access_counter:
      name: "5 Zugriffszähler"
    status_text:
      name: "5 Status"


  - platform: ultramaxx
    id: ultramaxx_6
    uart_id: i2c_uart_6

    serial_number:
      name: "6 Seriennummer"
    total_energy:
      name: "6 Gesamtenergie"
    total_volume:
      name: "6 Gesamtvolumen"
    power:
      name: "6 Leistung"
    flow:
      name: "6 Flow"
    temp_flow:
      name: "6 Vorlauf Temperatur"
    temp_return:
      name: "6 Rücklauf Temperatur"
    temp_diff:
      name: "6 Temperatur Differenz"
    meter_time:
      name: "6 Zeitstempel"
    operating_time:
      name: "6 Betriebszeit"
    firmware_version:
      name: "6 Firmware Version"
    software_version:
      name: "6 Software Version"
    access_counter:
      name: "6 Zugriffszähler"
    status_text:
      name: "6 Status"


  # =========================
  # Modul 4 – Adresse 0x70
  # =========================

  - platform: ultramaxx
    id: ultramaxx_7
    uart_id: i2c_uart_7

    serial_number:
      name: "7 Seriennummer"
    total_energy:
      name: "7 Gesamtenergie"
    total_volume:
      name: "7 Gesamtvolumen"
    power:
      name: "7 Leistung"
    flow:
      name: "7 Flow"
    temp_flow:
      name: "7 Vorlauf Temperatur"
    temp_return:
      name: "7 Rücklauf Temperatur"
    temp_diff:
      name: "7 Temperatur Differenz"
    meter_time:
      name: "7 Zeitstempel"
    operating_time:
      name: "7 Betriebszeit"
    firmware_version:
      name: "7 Firmware Version"
    software_version:
      name: "7 Software Version"
    access_counter:
      name: "7 Zugriffszähler"
    status_text:
      name: "7 Status"


  - platform: ultramaxx
    id: ultramaxx_8
    uart_id: i2c_uart_8

    serial_number:
      name: "8 Seriennummer"
    total_energy:
      name: "8 Gesamtenergie"
    total_volume:
      name: "8 Gesamtvolumen"
    power:
      name: "8 Leistung"
    flow:
      name: "8 Flow"
    temp_flow:
      name: "8 Vorlauf Temperatur"
    temp_return:
      name: "8 Rücklauf Temperatur"
    temp_diff:
      name: "8 Temperatur Differenz"
    meter_time:
      name: "8 Zeitstempel"
    operating_time:
      name: "8 Betriebszeit"
    firmware_version:
      name: "8 Firmware Version"
    software_version:
      name: "8 Software Version"
    access_counter:
      name: "8 Zugriffszähler"
    status_text:
      name: "8 Status"


      
